### ISSUE TITLE
Many issues with prototypes in 5.3

### ISSUE THREAD

**Issue by GodefroyClair** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#267]
The prototype of readnumber function (`struct digit *readNumber(void);`) is missing and I can't add it without having this error.
```
New `Error - It appears you have modified restricted code.` this time in the activity "update nodes in a linked list" of 5.3
```
Thanks for your help!

Here is my code:
```
#include <stdio.h>
#include <stdlib.h>

struct digit {
    int num;
    struct digit *next;
};

struct digit *createDigit(int dig);
struct digit *append(struct digit * end, struct digit * newDigptr);
void printNumber(struct digit *start);
void freeNumber(struct digit *start);
int divisibleByThree(struct digit * start);
//Add your own function prototypes here
struct digit *readNumber(void);
int changeThrees(struct digit * start);
int main(void) {
    struct digit *start;
    start = readNumber();

    printf("The number ");
    printNumber(start);
    printf("was modified in %d places.\n", changeThrees(start));

    printf("The new number is ");
    printNumber(start);
    freeNumber(start);

    return 0;
}

struct digit *createDigit(int dig) {
    struct digit *ptr;
    ptr = (struct digit *) malloc(sizeof(struct digit));
    ptr->num = dig;
    ptr->next = NULL;
    return ptr;
}

struct digit *append(struct digit * end, struct digit * newDigptr) {
    end->next = newDigptr;
    return(end->next);
}

void printNumber(struct digit *start) {
    struct digit * ptr = start;
    while (ptr!=NULL) {
        printf("%d", ptr->num);
        ptr = ptr->next;
    }
    printf("\n");
}

void freeNumber(struct digit *start) {
    struct digit * ptr = start;
    struct digit * tmp;
    while (ptr!=NULL) {
        tmp = ptr->next;
        free(ptr);
        ptr = tmp;
    }
}

struct digit *readNumber(void) {
    char c;
    int d;
    struct digit *start, *end, *newptr;
    start = NULL;
    scanf("%c", &c);
    while (c != '\n') {
        d = c-48;
        newptr = createDigit(d);
        if (start == NULL) {
            start = newptr;
            end = start;
        } else {
            end = append(end, newptr);
        }
        scanf("%c", &c);
    }
    return(start);
}

int divisibleByThree(struct digit * start) {
    struct digit * ptr = start;
    int qsum = 0;
    while (ptr!=NULL) {
        qsum += ptr->num;
        ptr = ptr->next;
    }
    if (qsum%3==0) return 1;
    else return 0;
}

// Write your changeThrees() function here
int changeThrees(struct digit * start) {
    struct digit * ptr = start;
    int count = 0;
    while (ptr!=NULL) {
        if(ptr->num == 3) {
          ptr->num = 9;
          count++;
        }
        ptr = ptr->next;
    }
    return count;
}
```

**Comment by deladan** [comment]
Hi!  
A learner has just posted a message about this issue.

**Comment by deladan** [comment]
There's a lot of differences between the provided code and the one given in the solution, which passes.  
In particular about prototypes.
First, the prototype for readNumber is missing but that was already reported.
Some are written with the name of the arguments, or wihout spaces between * and the name of the function.
(By the way, that is quite inconsistent because even in the solution some have the name of the argument, some don't).
There are also blank lines in the main function which don't appear in the solution.
And there is a missing space in the definition of the function append (between * and the name of the function).  
If one corrects all of this, the code passes.
EDIT: It actually seems that it's the last point which only causes the issue.

**Comment by deladan** [comment]
The issue is still here, and some learners begin to lose patience.
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/discussion/forum/73538f017994a566e36d48948620d55abc9dedfa/threads/5bb884b64265a408e700030c
As I said earlier, the provided code differs from what is expected.  
But what seems to block the validation here is that there is no space between * and append in the definition of the function append.  
Couldn't it be easily added in the provided code?   
The readNumber prototype is also missing, but one can add it without problem.

**Comment by remisharrock** [comment]
@chrissmiller could you take a look at this ?

**Comment by petraBT** [comment]
@chrissmiller  this is about the activity "update nodes in a list" (updateNumber in C105W3 in taskeditor). Could you add the prototype for readnumber() as well as the space between * and append in the append function definition in the pre-populated code?

**Comment by chrissmiller** [comment]
Hi all,

So sorry for the delay with this; I thought I had fixed this checker but missed a piece of the restricted material. It appears to be working now!

**Comment by GodefroyClair** [comment]
@chrissmiller : Just checked, it's all good for me! 👍
