### ISSUE TITLE
String declared with constant size

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#306]
A learner has tried declare a string using a constant.
The grader didn't appreciate it.  
I've tried to submit his or her code and indeed, it's not accepted, even though working well on my computer.
Is it a bug?  
I didn't remember that constants were introduced in the course by the way. That could explain why the grader isn't implemented to accept that solution.
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/discussion/forum/a84f3092aab4a70eac7f7ed1b26d3be762306c20/threads/5bb76d3db41e6e085500023f

**Comment by petraBT** [comment]
We have not introduced constants in this course, and writing auto-graders that predict every way in which a student might code given some prior knowledge is indeed difficult. In this particular case, however, the student's solution is actually incorrect as they declare an array of size 2 (which is way to small to hold the potentially 100 characters plus the null terminator they are asked to hold). 
@chrissmiller I don't see an easy way to check for the correct size if the solution uses constants - do you?
@deladan Might you delete the student's code from the discussion forum so as to not give away the solution?

**Comment by deladan** [comment]
In fact, he has tested its code with a constant equal to 101 before 2, with the same error.
And I tested it myself.  
But I agree with you, it's very difficult to predict all possible answers.  
I edited the post to delete the solution.

**Comment by petraBT** [comment]
@deladan Thank you!

**Comment by chrissmiller** [comment]
@petraBT I've modified the checker to just look for the number 101 in the code; it's a bit less strict of a check but it should find it if it's in a constant (though it will also find it if a student declares a variable equal to 101 and then puts the variable in the array even though that's a variable length array aka not ANSI C). If you want more strict checking, we could alternatively check with Michel about compilation and see if we can access the code after preprocessing? That way we could just look at the code after constants are replaced. Not certain whether or not that's worth the coding complexity though. Let me know your thoughts!

For now though, this issue is addressed.
