### ISSUE TITLE
rephrasing a problem statement (monitoring a chemical experience)?

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#339]
A learner advise to rephrase the problem statement of this activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/c994b80204d747b6aa16ad991f4b1904/bcaeeafdf43b417e910a6ac07da4bd83/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40c91e5d9883c54d3b841c578776d54f91
He doesn't think that input should go on after an "alert" because the user will stop measurement in this case.  
Maybe you can precise that the program is automatically fed with these measures?
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/discussion/forum/a72c02975d539216f42f9db112a729271a6c6bf4/threads/5bbf4b60fb45b208370007b7

**Comment by petraBT** [comment]
Thank you! I have attempted to make the problem statement even clearer...

Another comment caught my eye though: @chrissmiller we should add a test in which the minimum temperature is below -999 so that we can distinguish whether a student is actually checking whether -999 has been sent (rather than only checking on the temperature range). If we do add such a test we should also add an example of the following type to the problem statement:

Input: -5000 40
38 27 -999 22

Output:
Normal
Normal

We may have to then also explain that the device will simply continue sending temperatures even after the reaction is over - not great. 

Actually, I don't really like this idea at all. How about instead of adding another test we simply do a regex check on whether -999 appears somewhere in the code? Not water-proof but better than what we have now?

**Comment by deladan** [comment]
I've reported this issue in #334

**Comment by chrissmiller** [comment]
Added the proper check!
