### ISSUE TITLE
lack of strictness in the solution for the activity about procrastinating (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#365]
In the activity perform simple arithmetic, we're asked to calculate X, Y and Z values and use the %d format specifier for printing them, but the solution doesn't do that for X.  
And as the solution is accepted by the grader, I'd think that the grader doesn't test that.
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccf660cc6a1141e0a9bebfc515ce320a/8886730e8869426bbdcab50815cbeedf/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40448236f24ba64b4aa314ae93827ab3bd

**Comment by klotsy** [comment]
tu parles bien du fait que la solution ne calcule pas (25-23) mais utilise directement 2 ?

**Comment by deladan** [comment]
@klotsy 
Oui, c'est bien ça

**Comment by chrissmiller** [comment]
Thanks @deladan - the checker here does verify that the student doesn't hardcode answers, but it's hard to check for a hardcoded 2 vs 25-23 so I think we're accepting that students may hardcode the number of days (especially because it's such a simple calculation - forcing them to code the calculation may frustrate learners). I have updated the solution to include calculations for it though just so students don't get confused by that!
