### ISSUE TITLE
Issue with Taksgrader (course2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#408]
In the activity about swapping first and last names, Taskgrader is accepting code which doesn't do the job.  
Here's the erroneous code from some learner:  
```
#include <stdio.h>
int main(void)
{
	int numi = 0;
	char firstName[101];
	char secondName[101];
	int i;
	scanf("%d%s%s", &numi, firstName, secondName);
	while(numi >= 0){
	scanf("%s%s", firstName, secondName);
	for(i = 0; i < numi; i++){
	printf("%s %s\n", secondName, firstName);
	}
	}
return 0;
}
```
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/f2a41407085b4e8c8a5604123388ef33/914396655d9144bfaf7bd9710bc7415e/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%4014f2b324a7ea47868093d86f2d627272

**Comment by chrissmiller** [comment]
I really have no clue why taskgrader is accepting the solution since it's clearly producing an infinite loop... I've added another test which this fails so that users cannot receive a passing grade with this, but also passed the issue along to Michel since it shouldn't be grading any infinite loop code correctly. Will update with his response.

**Comment by chrissmiller** [comment]
Taskgrader is not able to identify timeout errors/distinguish them from code errors right now but I have set this one so that the grader script will no longer run when a timeout like that occurs and they will receive a zero!
