### ISSUE TITLE
Some remark from learner about unit converter (course 3)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#422]
`You want us to convert meters, grams, Celsius into feet, pounds, Fahrenheit. It means metric to imperial. However, your conversion rules give us formulas on 1 foot (imperial), grams (metric), and Fahrenheit (imperial). Why?`
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/discussion/forum/022af50ca31fe27dc07df110a366aea6a28df050/threads/5c0c19c9ef5b3309c8002a93
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/9afb1233a3d74a62acc1625236e57a96/07d4663586b74bd6abd7b94bf3326474/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2018%2Btype%40discussion%2Bblock%407122ea906669412b907fdb23bc26c0da

**Comment by chrissmiller** [comment]
I switched over the meters/feet one - although in this user's rationale there will still be an inconsistency with the Fahrenheit one, all of them are now designed to multiply a metric value by the given number (or otherwise modify as in the temp case) and switch it to imperial which I think is now consistent with the problem statement.
