### ISSUE TITLE
Syntactic sugar (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#430]
Several learners were confused by the use of the += operator in the solution of the activity about robots.  
I can't remember if it was introduced in the course, but if not, maybe it should be in a future version of the course (or the solution modified) ?  

Link to the activity:  https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccf660cc6a1141e0a9bebfc515ce320a/76cd4b61bfd641de982b5f4f9a169ee6/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%4002bc7c036e874cd4b15818185a8d1c2e

**Comment by chrissmiller** [comment]
@petraBT I think this is probably a content issue, but should I switch over the solution to sum = sum +... instead of sum +=... if the += syntax has not been introduced yet? If it isn't introduced at all I'm inclined to leave it in since other solutions throughout other courses use it (and obviously it is the more compact format).

**Comment by petraBT** [comment]
@chrissmiller I honestly don't remember when we introduce the += notation - I think (hope...) it is around the time when we introduce things like i++ (loops?). So if we could simply get rid of this syntax in solutions for course 1 that would be great.

**Comment by chrissmiller** [comment]
Fixed solution
