### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#588]
From some learner in forum in course 6, in [section about Linux history](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/fa3b199b4927423f90a0f80550b0d4c3/e241fa2b0ca1495db74ce4c94b47820d/7?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%400818d3c0c1d24139a80adf315ef07c8f), Linus Torvalds is misspelled in Linus Torvals

**Comment by catherinechoww** [comment]
I believe it's not a typo and it's just a trick question? Since it's not the correct answer anyway - they were probably just providing a name that sounded familiar but wasn't what they were looking for. To be confirmed at next meeting.

Assignment can be found here:
[https://telecom-paris.france-ioi.org/en/a/2253450618013476301;p=4702,458602124916982205,4046614598589644961,2826323308687128226,798024880482281306,2091679065661145751;pa=0](url)

Screenshot of question:

<img width="383" alt="Screen Shot 2023-04-27 at 12 43 00 PM" src="https://user-images.githubusercontent.com/98115742/235006475-848d8e42-dd4d-417a-b51f-7a4acfa62cb0.png">
