### ISSUE TITLE
Activity "put lines in the correct order" needs some work

### ISSUE THREAD

**Issue by petraBT** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#606]
In MOOC1, Course  Unit 1.1: Printing, loops, and comments  Structure of a simple C program  Activity: put lines in the correct order, the problem statement has jumbled up code that needs to be corrected: One line reads

}int main(){

The closing brace } should be on a separate line. The rest should read 

int main(void) { 

Also, the directions indicate that the learner is to comment the code but the checker does not account for that. I received a perfect score without a single comment.

**Comment by AadhyaKocha** [comment]
I have fixed the brace formatting. The test input file on Taksgrader for it as of now seems empty but I will try finding that file. If not, I will create a new test for it.

**Comment by petraBT** [comment]
I have refreshed multiple times but have not seen a change - not sure if this is just my computer acting wonky or if the change didn't take? I am still seeing the issues:

![Screen Shot 2020-02-21 at 7 45 43 AM](https://user-images.githubusercontent.com/33522257/75035832-64aea100-547e-11ea-99aa-c10f3570c4f3.png)

**Comment by AadhyaKocha** [comment]
This is weird because when I edit it in Taskgrader and put the new link in studio edX it changed but it isn't changing this. Taskgrader is reflecting the code change but when I save and import it stops reflecting the change and removed the space again. So I am not sure why it looks like this sadly.

As for the comments not being needed by the checker, the tests that we can program on there only has to do with the inputs and outputs rather than the learner code required for that output. The comments are already in the solution but because of how the checker is coded, it ignores the comments or lack of comments while checking the accuracy of the code. I cannot change that from my end as that is how the Taskgrader grading aspect works as of now and there is no option to make comments necessary.

**Comment by petraBT** [comment]
@remisharrock and @EllaHa : This is very strange - the task, though updated in taskeditor, does not update in edX (neither does it update in the "test task" preview - so this has nothing to do with edX). Should this be escalated to Michel?

**Comment by mblockelet** [comment]
Hello, the issue is now fixed, it was related to old issues with our task-editor.

Some time ago, the task-editor was generating files `index_fr.html` and `index_fa.html` by mistake, but we removed that. It isn't supposed to affect anything, but one of these files was malformed in the folder of this task, and caused a mix during import, which would use the old `index_fr.html` file instead of the newly updated `index.html` file.

I removed all `index_fr.html` and `index_fa.html` files from the repository, and now the import behaves properly.

Sorry for the issue.

On another note, it is possible to add code in the checker to check for comments, I can take care of it if you want, at least to give an example of how to do it.

**Comment by petraBT** [comment]
Thank you so much, Michel! Yes, please do add the code to check for comments so that we can learn how to do this. Thank you!!

**Comment by mblockelet** [comment]
Hi, I just modified the code to include the checker which checks for comments. Don't hesitate to modify the checker to better suit your needs, or put a more verbose message when no comments are included!

**Comment by petraBT** [comment]
Fantastic - thank you!!
