### ISSUE TITLE
Submission Error in MOOC 1.2 V2

### ISSUE THREAD

**Issue by rserranosmith** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#644]
There is an issue with [Unit 1.2: Integers, variables and user input > Using variables > Activity: assign, re-assign, and update a variable](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/05c2e747f2bc429d979fd2c529f5b8a1/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40a0453e1ed42a4c0f9860d38ffcb3b74f) when the user tries to submit their solution, the system does not allow them, and instead prints "There was an error while submitting this answer, please try again in a few minutes." To replicate this issue, the solutions used were:

1. 34
2. 68
3. 40
4. 22

Below is a screenshot of the error received
<img width="1011" alt="Screen Shot 2020-07-08 at 12 08 43 AM" src="https://user-images.githubusercontent.com/49991645/86883761-c9763b00-c0af-11ea-911f-4e18e45ec887.png">

**Comment by rserranosmith** [comment]
Seems to be occurring in every quiz activity in MOOC 1

[Activity: find special characters on the keyboard](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/066b0480b13046e396208ef51d5c790b/09151bec3f5c43f2b56e181e2ad87d03/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%4005f4696417864b149b69edc232963bbe)

[Activity: declare and name variables](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/486dacf4bd094519afe1c91af2e17fee/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40cbacb57afab143ec93b53e6c5a1a8551)

**Comment by AadhyaKocha** [comment]
This error is showing in all these three quizzes no matter what the solution is. But this student's answer is right. I thought it could be because of user input but [Activity: declare and name variables](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/486dacf4bd094519afe1c91af2e17fee/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40cbacb57afab143ec93b53e6c5a1a8551) is an option selection quiz. Additionally if it helps- this 'Declare and Name Variables' quiz was working right for me earlier and I successfully submitted it just 2 weeks ago. Couldn't figure out why these quizzes are not working though.

**Comment by mblockelet** [comment]
Hello, I fixed it, it was an issue with a SSL certificated which expired and the new version was not reloaded properly. All quizzes should work again now, sorry for the issue!

**Comment by AadhyaKocha** [comment]
Seems to be working, thank you!
