### ISSUE TITLE
About ANSI C (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#684]
Some learner asks in the forum:  
Why are you teaching an obsolete version of C from 1989 instead of a more modern (the newest is from 2018) version? And why do you not specify in the course overview that you teach this very old version?

Maybe this could be indeed added to the course overview?

Link to the thread in the forum: [https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/79e6816021eea4fbfc6bf39ba80ecf86298d1731/threads/600c91a7f012b7082b64a12a](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/79e6816021eea4fbfc6bf39ba80ecf86298d1731/threads/600c91a7f012b7082b64a12a)

**Comment by AadhyaKocha** [comment]
Made this note for the first two loop quizzes:
"Remember to declare the variable used in the loop outside the loop in this quiz. So if using variable i, declare that it is an integer before starting the loop. This is only so that the grader grades you correctly for this quiz. As you move on with the quizzes in this course you will be able to compress the code by declaring int within the loop itself."
