### ISSUE TITLE
Suggestion about controlling an epidemic activity

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#717]
For [this activity](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020+type@sequential+block@51bd0abbbc894fe8b3623ce03d05fc90/block-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020+type@vertical+block@9c11e06096674f2ba4ca79ffd0eb87d5), there are a lot of learners who failed to understand that all infected people contaminate two other ones each day.  
Issue is that the two provided examples give same results in both situation (when all infected people go on contaminating each day, and when infected people contaminate only once).
Suggestion would be to add another example, with a greater population, so that both situations differ and learners can find that their program doesn't do what they want before submitting it (and asking for help in the forum).

**Comment by marchill23** [comment]
We could include an example with a population of 100 people. So, on day one, 1 person is infected. On day two, they contaminate 2 people and now 3 people are infected. On day three, the 3 people contaminate 6 people (2 people each) and now 9 people are infected. On day four, the 9 people contaminate 18 people, and now 27 people are infected. On day five, the 27 people contaminate 54 people, and now 81 people are infected. On day six, the 81 people have the potential to contaminate 162 people, but since the population is 100, all 100 people would now be infected. So, the program would output '6' if the user inputs '100'.

**Comment by AadhyaKocha** [comment]
Added

**Comment by deladan** [comment]
Hello @AadhyaKocha ,
Example was added but with a typo, as input should be 100 and not 10.

**Comment by deladan** [comment]
Issue is still there, and was reported by some learner again in forum.

**Comment by AadhyaKocha** [comment]
Corrected example.
