### ISSUE TITLE
People not able to get 100%

### ISSUE THREAD

**Issue by EllaHa** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#775]
https://www.coursera.org/learn/c-programming-getting-started/gradedLti/Sttgx/define-key-terms
I've received about eight comments (anonymous flags and forum posts) about being unable to complete this activity. These users are getting only 75%. See an example of such a complaint below.

https://www.coursera.org/learn/c-programming-getting-started/discussions/forums/XDKc69m5Eeukzwp6-55i3w/threads/CEmOFleiEe2IwAoA10_dbQ

I'm not sure if they're all just unable to figure out the correct answer. However, I'm worried that because a lot of these complaints arose around the same time, that there might be a bug similar to the one Josh found, where some people are able to get 100% (Remi, for example), while I am selecting the correct answer and unable to get full credit.
Would some of you mind trying it out to see if it's a bug?

**Comment by EllaHa** [comment]
It sounds we are not able to reproduce this issue. Several of us tried and could get 100%. So it sounds this not a bug. To be sure of what is happening for these students we need to ask them a screenshot. Please ask them for the screenshot.

**Comment by catherinechoww** [comment]
Those who submitted the flags never got back to me. However, I've had multiple people recently on the discussion forum claiming that there was an error with the quiz because they were unable to get 100%. When I ask them to share a screenshot, I found they were just answering the quiz incorrectly.

There seems to be no bug on this quiz.
