### ISSUE TITLE
MOOC 6 Week 2 Quiz Score Not Updating

### ISSUE THREAD

**Issue by Apaquet37** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#794]
A learner has been taking the quiz and scoring 100/100, but it does not update on their profile and continues to show as incomplete.

[https://www.coursera.org/learn/linux-basics-the-command-line-interface/discussions/forums/3EsZCrmUEeyBoBL7F1DbTw/threads/IoDzeDcSEe-eFgr_9lJ0ZQ](https://www.coursera.org/learn/linux-basics-the-command-line-interface/discussions/forums/3EsZCrmUEeyBoBL7F1DbTw/threads/IoDzeDcSEe-eFgr_9lJ0ZQ
)

<img width="914" alt="Screenshot 2024-07-09 at 10 30 29 PM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/48455283/7fb10e19-afc0-4ccb-b845-393e2aed7a91">

<img width="284" alt="Screenshot 2024-07-09 at 10 33 00 PM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/48455283/fd4df0fe-d07b-440e-b0b4-a75c432cedbb">

**Comment by remisharrock** [comment]
thanks for reporting, I'll inform the devs now !

**Comment by mblockelet** [comment]
Hi @Apaquet37 , @remisharrock ,

There are two unrelated issues there, but the main issue is that the learner didn't realise that there are two quizzes to answer, and probably only solved one. More details below.

The 404 error reported is "normal" with the current way the quiz work, the file is deleted then kept on the backend, but I will change that so that users aren't startled by the 404 error and think the issues come from there.

About the "main issue" :

* there are two quizzes behind that item, so by solving only one quiz, the user only gets 50%
* it's partly a Coursera issue, because in my opinion it's not clear to the user that they only got 50% of the grade, and seeing they got only 50% might prompt the learner to check for other quizzes (that could be a feedback to give them so they improve their interface)
* on the quiz side, you could use the `quiz_settings.display_move_to_next` option to display a button "Next question" once the quiz is answered, to prompt the learner to move onto the next quiz

Either way, there shouldn't be any modification to make for the learner to be able to complete this item (and the course), they just need to complete the second quiz of the item.

If there is any other issue, please keep me updated!

**Comment by remisharrock** [comment]
Thabks @mblockelet for investigating, @Apaquet37 could you reach out to the student and explain the situation? Could you also check that there are indeed two quizzes to answer? Thanks !

**Comment by Apaquet37** [comment]
@remisharrock Yep! I'll let them know. I just checked, and there are indeed two quizzes.

**Comment by Apaquet37** [comment]
Issue should be resolved
